# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Learn TDD
email: tdd@need-bee.com
description: > # this means to ignore newlines until "baseurl:"
  Learn test-driven development in your framework of choice.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://learntdd.in" # the base hostname & protocol for your site
twitter_username: CodingItWrong
github_username:  learn-tdd-in
google_analytics: 'UA-80822752-1'
port: 4002

# Build settings
markdown: kramdown
theme: minima

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
